### PR TITLE
Proposal: storybook container changes

### PR DESCRIPTION
**Pull request by Klaas058**
Storybook docs generation changes.

I propose to add the ability to put classes on the component container by passing `containerClassNames` or `defaultContainerClassName` to the Storybook parameters.
This allows components to remove their wrapping containers from the story (if they have them) thereby removing the clutter and use-case specific code from the code example.

For example, current example code of current components with containers:

```jsx
<div className="flex w-full justify-center p-4 items-center font-sans component-preview">
  <Menu {...args}>
    <Menu.Item>
      <a>Item 1</a>
    </Menu.Item>
    <Menu.Item>
      <a>Item 2</a>
    </Menu.Item>
  </Menu>
</div>
```
Will now be cleaner and not show any use-case specific classes for the storybook example:
```jsx
<Menu {...args}>
  <Menu.Item>
    <a>Item 1</a>
  </Menu.Item>
  <Menu.Item>
    <a>Item 2</a>
  </Menu.Item>
</Menu>
```

This:
1. Improves the quality of our code examples by removing clutter and use-case specific storybook containers
2. Removes the current used containers to have all components use the same default container (like daisyui examples also do)
3. Make future changes to the component preview easier since its all managed by the same container

Let me know what you think, all the naming and approach can be adjusted but I think the idea brings value.

ps. All classes removed and not replaced in this PR are redundant because they were already managed by the story component container

### CODE REVIEW

**Review by benjitrosch — COMMENTED** [review]
On the contrary: I think MORE of our Storybook's should expose the classes used in setting up the examples 😄 

Displaying the tailwind classnames allows users to see what styling we use in each example, and therefore how they can replicate the example themselves. By hiding the classnames we are not being as transparent as we can about the components form -- and users might be confused why components render differently in their projects.

**Comment by Klaas058** [comment]
Hi @benjitrosch, interesting, I wasn't expecting that.

I agree with you at some level, can you help me to clarify what should and should not be included?

For example the current `Input` component:
```jsx
    <div className="flex w-full component-preview p-4 items-center justify-center gap-2 font-sans">
      <Input {...args} />
    </div>
```
Purely taking about the `container` because I think the story itself already can be improved compared to the [input of daisyui](https://daisyui.com/components/input/#text-input)

Looking at the container, all these classes: `flex w-full component-preview p-4 items-center justify-center gap-2` are all already default for a component preview by the story layout [container](https://github.com/daisyui/react-daisyui/blob/main/.storybook/story-layout.js#L71). All except for the last one `font-sans`.

To me, looking at that list, it doesn't give the user any useful information.
However, the classes that are hidden in the `{...args}` are: `w-full max-w-xs`, these are useful to know. I am not looking to remove those.

But classes like `font-sans` and `mb-40` that only effect the __container__ and have nothing todo with the component itself, should not be shown to the user (just like daisyui docs do), in my opinion.

What do you think?

Also, what do you think about setting the font in our docs to `font-sans` by default, that would make us in-line with daisyui default and make the current 11 components that set this manually automatically look inline to the original?

**Comment by benjitrosch** [comment]
@Klaas058 sorry for the late reply, have had a busy couple weeks!

I 100% agree that the current classnames are too much and should reflect the examples from daisyui.com. Part of that, like you said, would mean beefing up the story-layout container and setting the default font etc.

So seems like a mix between the two-- removing redundant classnames but still showing the styles necessary for each story!

**Comment by Klaas058** [comment]
Hi @benjitrosch don't worry about it. I think I see what you're getting at. 

I will update the PR to reflect this philosophy

**Comment by Klaas058** [comment]
Hi @benjitrosch, I went through the PR again trying to implement what we talked about, but it came down to just making the `font-sans` default.
This resulted in quite a lot of changes in stories of components that put on `font-sans` themselves, now all components have the same font as **DaisyUI** has in their docs. (for the diff see [here](https://github.com/daisyui/react-daisyui/pull/232/commits/d16754c388dc609ea932c49a85a28b3eeb623ef8))

Though this doesn't make the stories themselves any better.
Looking at it now I think this is because of the `{...args}` splitting.

This is the DaisyUI JSX:
```jsx
<input type="text" placeholder="Type here" className="input w-full max-w-xs" />
```

This is ours:
```jsx
<Input {...args} />
```

The `className` is not visible in the preview because it is 'hidden' in the `{...args}`, the user can see the props, but has to look them up in the props section.

I think something like this is much more informative on first glance:
```jsx
<Input className='w-full max-w-xs' {...args} />
```
This way you have the classes both in the preview and the controls.
But it has the drawback that if you change the `className` in the controls, the preview doesn't update it.
It will work because it overrides the default `className` but it is kind of 'ugly'.

I wonder if there is a way to compute the jsx preview on runtime instead of build time.
Maybe there is a Storybook addon for that?

What do you think?

**Pull request closed without merging**
