### PR TITLE
fix(Stats): removed incorrect import on examples

### PR DESCRIPTION
**Pull request by dev0T**
Adresses #338.

The examples were not using the library correctly, making use of internal imports.

### CODE REVIEW

**Review by benjitrosch — APPROVED** [review]
Thanks for finding and fixing this. The subcomponents look a little cumbersome (and ugly) in this case so maybe worth revisiting how we handle the `<Stats>` component in the future.

We could probably combine `Stat` and `Item` into one component. Can't remember why they were ever separate components to begin with.

**Comment by dev0T** [comment]
> Thanks for finding and fixing this. The subcomponents look a little cumbersome (and ugly) in this case so maybe worth revisiting how we handle the `<Stats>` component in the future.
> 
> We could probably combine `Stat` and `Item` into one component. Can't remember why they were ever separate components to begin with.

I will take a look into that today and see what I can do!

**Comment by dev0T** [comment]
After giving it a further look, I don't think combining `Stat` and `Item` is a good approach because you need to be able to provide classNames for the different parts of the `Stat` (Similar to the current lack of TableCell). I'd like to suggest an approach similar to `NavBar` sections where instead of providing `Stats.Stat.Item` along with a props variant, one would decide between `Stats.Stat.Title`, `Stats.Stat.Value`, etc.

I'd suggest merging this to correct the docs usage for now and after deciding the new component structure change it for a new version since it will also be a breaking change. What do you think @benjitrosch?

Edit: I created a PR so you can take a look! #341

**Comment by benjitrosch** [comment]
Thanks for looking into that. We can't update the docs at the moment since they're broken and are reverted to a previous release. So if it's just for the sake of updating the docs, we're unfortunately out of luck. On the bright side, that gives us time to come up with a better solution @dev0T 😅

**Comment by dev0T** [comment]
> Thanks for looking into that. We can't update the docs at the moment since they're broken and are reverted to a previous release. So if it's just for the sake of updating the docs, we're unfortunately out of luck. On the bright side, that gives us time to come up with a better solution @dev0T 😅

I forgot about that issue! haha

I did create a new PR with my suggested approach, take a look whenever you have the time and let me know if you have any questions! #341

**Comment by dev0T** [comment]
Hey @benjitrosch! Since the docs aren't broken anymore, can this be merged? Thanks!

**Pull request merged**
