### PR TITLE
Proposal: Rebuild Rating component to a controlled React component

### PR DESCRIPTION
**Pull request by Klaas058**
Component: Rating
Issue: Rating component does not work as expected #215

As mentioned in issue #215 the Rating component does not work as expected.

This is caused by the way React handles its input component. 
When React renders an input it can either be a [controlled](https://reactjs.org/docs/forms.html#controlled-components) component or an [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) component.
The big difference here is that `controlled` components are managed by the React state, the `uncontrolled` components are not.

When passing the `checked` prop to an `input`, React makes the input a `controlled` component and it expects an `onChange` handler to handle the check change.
When it doesn't receive an `onChange` handler, the `input` becomes an `uncontrolled` component (and expects to get a readOnly prop to confirm) and places the `checked` prop as `defaultChecked`.

This messes up the default behavior of DaisyUI because now the `checked` prop is not used, therefore [the conditional opacity class](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/rating.css#L14) that makes the Rating selected/unselected, doesn't work.

Please correct me if I'm wrong on this but this sounds like a decision that comes down to whether we want to be:
- A functional component library for DaisyUI components in React
or
- A convenient wrapper around DaisyUI to use in React

This PR contains a proposal to change the way the Rating component is used while maintaining the DaisyUI look and usage but making it functional in React.

The Rating component will now allow a `rating` prop, which is a `number` that corresponds with the amount of `Rating.Item`'s that should be selected.
It also now accepts an `onRatingChanged` function that is called when the rating changes.
The `checked` prop previously passed to the `Rating.Item` is now redundant.
The `hidden` state is now triggered by setting the `rating` prop to `0`, clearing the rating.

Looking forward to hearing your views on this, all feedback is welcome!

### CODE REVIEW

**Review by benjitrosch — COMMENTED** [review]
This is great, thank you for making this PR @Klaas058!

I'm happy to approve + merge it, just one small change: can we change the `rating` prop to `value` and `onRatingChange` to `onChange`, and then use `Omit<...>` to override the default behavior? That way the prop names are semantically closer to the native attributes.

**Comment by Klaas058** [comment]
Hi @benjitrosch, yes you are right `value` and `onChange` makes more sense. I will get on this sometime today.

**Comment by Klaas058** [comment]
Alright here it is.
Apologies for the delay, life happened.

I've refactored the `rating` prop to `value` and `onRatingChange` to `onChange`, omitting the default behaviour.

This PR is not a breaking change, all the current implementations will still work as expected because the new implementation solely relies on the `value` and `onChange` props.
However, because the `value` prop is required by typescript, it will give a warning.
Additionally, the `<Rating.Item className="rating-hidden" />` is no longer necessary when switching to the `controlled` version as per this PR. (this is now value = 0, as you would expect)

**Comment by Klaas058** [comment]
That was kind of stupid of me, I tried to rename the branch to `klaas058/rating-component-to-controlled-component` but that force closed the PR. Hope all is right again now.

**Review by benjitrosch — APPROVED** [review]

**Pull request merged**
